### ISSUE TITLE
"Cannot Show Password" in app

### ISSUE THREAD

**Issue by mtl** [mssun/passforios#110]
When I try to view pass files in the app, I receive an error: "Cannot Show Password" "Decrypted hash mismatch, invalid password." This seems to be coming from ObjectivePGP, and occurs both for passwords cloned from a git repository and passwords created within the app. However, the Safari integration works and is able to decrypt and copy the passwords just fine.

![img_1867](https://user-images.githubusercontent.com/41457/28261551-bf2d68fe-6aad-11e7-99ca-95fc1afeed5d.PNG)

Thank you very much for creating the app and providing it via the App Store.

**Comment by yishilin14** [comment]
Because the Safari integration works, I believe that you have cloned the repository correctly and imported the keys correctly.

One reason for seeing this error message is wrong passphrase for PGP keys. The Safari integration (aka extension) and the app itself does not share the passphrase for now (I am lazy...). Is it possible that you entered the correct passphrase in the extension and the wrong one by mistake in the app? Would you please click "try again" and enter the passphrase again?

**Comment by mtl** [comment]
Hi,

Yes, I've tried the passphrase many times in the app and receive the error every time. Because the safari extension is successful at decryption, I agree the PGP key and passphrase must be correct.

I imported the keys by pasting in the ASCII-Armor text if that helps. Thanks.

**Comment by jovrum** [comment]
I'm getting "Cannot Show Password" as well, but the error message that comes with it is:
```
Valid PublicKeyEncryptedSessionKeyPacket not found
```
I imported the keys by pasting the ASCII-armored text into the public and private key text boxes respectively. The private key is encrypted with a passphrase. I've tested that the passphrase I input is correct, but I still get the above error message.

Commented here instead of making a new ticket because of the title, but maybe this is a different issue.

**Comment by yishilin14** [comment]
@jovrum Thank you for the debug info. May I ask does the decryption function of the Safari extension work for you in your case?

**Comment by jovrum** [comment]
@yishilin14, I just tried it in the Safari extension and I get the same error message (the PublicKeyEncryptedSessionKeyPacket one). Up until that point it works fine (lists all my git-pulled passwords etc).

**Comment by yishilin14** [comment]
@jovrum It is possible that the PGP key you are using is not supported by the library Pass uses. Would you please tell us how to generate a pair of key of the same type (e.g., the commands) or provide a pair of key of the same type? Thanks.

**Comment by yishilin14** [comment]
@mtl I have no clue about how to reproduce your issue and investigate further. What version are you using now? Is this the first version that you have installed?

If no, would you please "erase all data (Settings->Advanced->Erase all)" and config again? I am trying to rule out the possibility of the migration bug.

**Comment by jovrum** [comment]
Initially I used the wrong key, so I set it up with the correct key but I get the same error message. I've also verified that the private key passphrase is correct for the new key.

Maybe it's because my keys are 4096 bit?

**Comment by mtl** [comment]
It's working for me now. Just updated the app, I think it was the July 17, 2017 update, and all is well. Thanks!
