### ISSUE TITLE
Indicate unparsed raw data

### ISSUE THREAD

**Issue by goerz** [mssun/passforios#132]
Currently, lines that match the format `key: value` are shown in the "Additions" section. However, lines that don't match the pattern are simply ignored. They are still available through "Show Raw", but there is no indication that there is additional "raw" information.

I would propose to have a visual indicator when there are any lines that cannot be parsed into the normal interface (possibly just some additional text in the "Show Raw" button).

**Comment by mssun** [comment]
Sure, that's a very good idea.

We can put a little **red dot** on the "Show Raw" button to indicate that there are something which cannot be parsed and shown.

BTW, do you think "Show Raw" is a good expression? Since I'm not a native English speaker, maybe it's not a proper word". How about "View in Raw" or "View Raw"?

**Comment by goerz** [comment]
"Show Raw" sounds pretty good to me (better than the two alternatives)

**Comment by mssun** [comment]
Good, thank you.

**Comment by SimplyDanny** [comment]
I just want to point out, that values which do not match the `key: value` syntax are not ignored. They are displayed using the keys `unknown 1`, `unknown 2`, ... and the content of the lines as values. Only if you activate "Hide Unknown Fields" they will be hidden.

**Comment by SimplyDanny** [comment]
Unfortunately, I am not able to add a "red dot" on the button. 🙈 Adding additional text to the button is simple, however. What I managed to do so far is this:

![hidden_fields](https://user-images.githubusercontent.com/16365760/49688838-737a9380-fb18-11e8-8d69-bdaa06b92287.png)

I called it "hidden field(s)" because it also takes hidden OTP fields into account (depending on the settings). That means, the number which is shown there consists of all hidden unparsable fields ("unknowns")  and all hidden OTP fields. If the password is an OTP token itself it is not considered as "hidden" and will therefore not be included.
