### ISSUE TITLE
support for multiline fields

### ISSUE THREAD

**Issue by goerz** [mssun/passforios#133]
I was wondering if there was a general consensus on how custom multiline fields should be written, e.g. a multiline address field. Do any other `pass` clients handle this explicitly? My most natural instinct would be to use indentation like this:

    ...
    number: 8234 2123 2345 1224
    address:
        Michael Goerz
        1 Main St
        City, CA 12345
    expiration date: 31/12/2018
    ...

Maybe such fields could be parsed and shown with multiple lines under "Additions"? This kind of multiline field was also what motivated me for feature request #132

**Comment by mssun** [comment]
The problem here is that there is no standard grammar to write an entry. We only support the "key: value" style in one line. For multiple-line fields, I think your proposal is pretty neat. Maybe we should define some format or use existing plain-text format (like yaml). In addition, we have to implement corresponding parser.

**Comment by SimplyDanny** [comment]
I think this issue can be closed.
