### ISSUE TITLE
Allow multiple URLs per item

### ISSUE THREAD

**Issue by newtonne** [mssun/passforios#161]
Firstly, I just wanted to say how much I love this app. It's rare to see an open source app really nail the user experience and adhere to the platform design conventions like Pass does.

I think it would be cool if Pass recognised multiple URLs for a single item for cases where you wish to use the same login credentials, but it doesn't make sense to create a new item. For example:

- citi.com, citibank.com
- amazon.com, amazon.co.uk

At the moment, it doesn't recognise the second `URL` item when you long press and select "Copy password and open link" and the extension doesn't offer to autofill if the domain names are different enough.

**Comment by yishilin14** [comment]
Thank you for your feedback. :-)

> It doesn't recognise the second URL item when you long press and select "Copy password and open link"

Oops, this is a bug. I didn't test this case. Will fix soon.

> and the extension doesn't offer to autofill if the domain names are different enough

passforios stores encrypted files only. It decrypts files only when a password is needed. 
Given a domain such as 'github.com', the extension tries to identify matching files according to their filenames.
In your case, one possible workaround would be renaming your files to common substring of URLs, such as "citi" and "amazon".

**Comment by SimplyDanny** [comment]
Even though the bug is fixed (the action "Copy Password & Open Link" is available on URL fields) the same action is now also possible on nearly every other field. Isn't this too much? The string "url" in the title of a field as the only indicator seems reasonable to me.

Besides that, if you tap "Copy Password & Open Link" on an arbitrary field (where the action is actually available) the first URL in the file will always be opened (not the one in the selected field).

I have created a PR addressing these points.
