### ISSUE TITLE
Swipe right to go back

### ISSUE THREAD

**Issue by chasgames** [mssun/passforios#178]
Hello

I really like the folders view, but it seems to be the only page missing swipe to go back.

To replicate:
Settings -> General -> Show Folders (enable)
Go into a folder
Back button appears top left, but swipe right won't work like it does in the settings and password pages.

Many Thanks!

**Comment by chasgames** [comment]
Strange not for me on iPhoneX also noticed the Back button doesn’t have the back arrow like on the other pages.

screen recording:

https://media0.giphy.com/media/7JO7aPPBq7fV9NzGjz/giphy.gif

**Comment by jaydisc** [comment]
I'm experiencing the same two symptoms on my X (the normal swipe back gesture not working, and no back arrow)

Pass 0.3.1 (15)
iOS 11.3

**Comment by yishilin14** [comment]
In fact, click a folder does not push a new view controller. Pass just refreshes the current view.

That's why the normal swipe back gesture does not work, and mssun mentioned "swipe right (a mimic gesture, not exactly same as the swipe in the Settings page)".

As for the back button, it is inserted by code. And that's why the "<" symbol is not there.

**Comment by jaydisc** [comment]
Bummer. It'd be nice if one day it switched to pushing the new view controller instead. As phones get bigger, those top navigation elements are harder and harder to reach.

**Comment by chasgames** [comment]
I see this is fixed now :)
