### ISSUE TITLE
Support for Yubikey NFC

### ISSUE THREAD

**Issue by antonlindstrom** [mssun/passforios#187]
Yubico released some information about an SDK for Yubikey NFC. It would be a really nice feature to support having the GPG key on a separate key and use the NFC reader to decrypt the password store.

https://www.yubico.com/2018/05/yubikey-comes-to-iphone-with-mobile-sdk-for-ios-and-lastpass-support/

I understand that this might be a very low priority feature but I thought I would add it here any way.

Thank you for all the hard work. The app is great!

**Comment by posix4e** [comment]
This is a Dup https://github.com/mssun/passforios/issues/42

**Comment by drdaeman** [comment]
Unfortunately, all YubiKey NFC iOS support offers is Yubico OTP - essentially, the same stuff that happens when you tap the token and it simulates typing that odd-looking long string. Except for over NFC.

There is no OpenPGP Card support, neither PIV or PKCS#11 - basically, there's nothing that's even theoretically usable for what pass needs to operate.

**Comment by yishilin14** [comment]
I am closing this and keeping #42
