### ISSUE TITLE
Is YAML formatting required for passforios ?

### ISSUE THREAD

**Issue by ypoxls** [mssun/passforios#190]
As a new user, I noticed that my multiline data does not appear correctly in passforios.
I can only get the data to appear if I choose the "RAW" data option after selecting an entry. 

I have colons, slashes, and other special characters in my multiline data (being interpreted as YAML).

The workaround I'm using is to add additional formatting (quotation) to all my entries - which is not required for Pass on the desktop.

So my question is about the use of YAML in passforios:
Commit: https://github.com/mssun/passforios/commit/caa5ce77a3feb4694308b511d094b4ea39ed71b9

Is YAML formatting required for passforios ?
Is there any way that I can choose not to use it? Because it is not a requirement to use Pass:

From the Pass website:
> The password store does not impose any particular schema or type of organization of your data, as it is simply a flat text file, which can contain arbitrary data.
[https://www.passwordstore.org](https://www.passwordstore.org)

I would like to avoid using a specific data format just to see my data properly in a client app.

Thank you for your hard work!

**Comment by yishilin14** [comment]
The short answer is no.

To support multi-line fields #133 ,  @SimplyDanny contributed some codes so that as long as an entry can be interpreted as a valid YAML file, it will be parsed as a YAML file. 

It works great for most cases. However, it seems like there are some compatibility issues for some corner cases. For example, the one fixed in 54c7acf65132ebacb13aebbc164836b22d58c730 and this issue.

I am thinking about adding an option to turn on/off YAML parsing somewhere.

**Comment by yishilin14** [comment]
BTW, do you mind to share with us what your multi-line fields look like?
Let me see whether it should be added as a special case where parsing as YAML should be turned off by default.

**Comment by ypoxls** [comment]
`a-very-long-and-complicated-password`
`Group: accounts`
`Filename: apple-myappleid`
`Title: Apple - MyAppleID`
`Username: name@domain.tld`
`URL: http://appleid.apple.com`
`Notes: // security hints: 1900/00/00 [security hint 1] [security hint 2] [security hint 3] // billing: street addtess City State ZipCode CellPhone`
