### ISSUE TITLE
Cannot run in simulator Xcode

### ISSUE THREAD

**Issue by sdekoning0** [mssun/passforios#268]
I cannot get the app running in the simulator, after following the README steps to update carthage and cocoapods I get the following error, any suggestions?

<img width="1143" alt="Screenshot 2019-05-21 at 15 56 10" src="https://user-images.githubusercontent.com/43604043/58102068-fda74780-7be0-11e9-96fc-6edd6651cb6d.png">

**Comment by yishilin14** [comment]
This is due to a bug in Cocoapods (see #247).

There are two workarounds:

1. Go back to use pod v1.5.3.
2. > "I could manually add in the ObjectivePGP.framework into the target's General settings in Xcode and that would work" https://github.com/mssun/passforios/issues/247#issue-414853551

I forgot to update the wiki page "Building Pass for iOS"...

**Comment by sdekoning0** [comment]
Thank you for the quick reply; indeed after downgrading cocoapods to version `1.5.3` it is working!
