### ISSUE TITLE
Keychain doesn't seem to get wiped on removal

### ISSUE THREAD

**Issue by machiel** [mssun/passforios#313]
I started playing around with Pass for iOS and set a passcode, then a few months later I decided to really start using it, but by this time I had forgotten my passcode.

I tried deleting the app, wiping all the database, but after re-install it still prompts me for my passcode.

Is there anything I can do myself in order to fix it?

**Comment by SimplyDanny** [comment]
Unfortunately, you cannot do anything yourself, except resetting your complete device. The passcode is stored in the keychain together with all the other sensitive data and only the app itself can change or delete it.

Also the app is not notified before it gets removed from a device. Thus, no code to clean things up can be executed prior to the removal. 

There is a workaround which uses the `UserDefaults` to check a flag on each start of the app for whether it has been freshly installed or not. It works because `UserDefaults` are removed from the device together with the app. With that the data in the keychain could potentially be removed on the first start.

I'm not yet sure whether it is a good idea to implement that.

**Comment by yishilin14** [comment]
I think we should add a way to reset the app when one forgets the passcode. For example, when one enters the wrong passcode for more than X times, a reset button shows up.

But I am kind of afraid that some users might be worried that others who can unlock the device could wiped the data... For me, it is not a problem because I am the only one who can unlock my device.

**Comment by machiel** [comment]
Oh, that would be great, I can imagine I won't be the only one forgetting the passcode. A method of resetting would be nice.

Personally I guess I'd prefer an accidental wipe over not being able to use the app at all, since you wouldn't lose actual data upon a reset.

**Comment by yishilin14** [comment]
I added a "Forget your passcode?" button in the passcode lock view in 35f599c45b0a97aa3f33d01ecde5f62b0a74fdd1. Users could reset the app after authentication with biometry or the device passcode. Authentication isn't required If there is no device passcode.

Leave comments if you guys have any opinions about this functionality.

**Comment by yishilin14** [comment]
It's in 0.8.0 (10) for TestFlight beta testing. 

@machiel  Drop an email to developer@passforios.mssun.me if you want to test.

**Comment by machiel** [comment]
Oh wow, that was quick, awesome! I sent an email for test flight access.

Thanks!

**Comment by machiel** [comment]
Works great, thanks a lot, I appreciate it :)

**Comment by mssun** [comment]
Closed, 0.8.0 (41) has been published in App Store.

Feel free to reopen this or create a new one if there are more related issues.
