### ISSUE TITLE
Clipboard text is cleared when "Password" field is tapped

### ISSUE THREAD

**Issue by jeyum2** [mssun/passforios#324]
Copied text in clipboard is cleared when tap "Password" field.
Is it intended? if so, can we implement option like "don't clear when tap password field"?

**Comment by SimplyDanny** [comment]
From within the code I cannot see why this would happen and on my device the issue is not reproducible. However, copied text is automatically cleared from the pasteboard after 45 seconds. This may be the reason why you miss it at some point.

**Comment by jeyum2** [comment]
I can reproduce it in this way, even if I complete these steps immediately after copying text(definitely within 45 seconds)

Tap "Add Password('+' Icon)" -> Tap "Password field" to show detailed options suck as "Get aMemorable One: xkpasswd" -> "Paste" on context menu -> Nothing happened and Clipboard text is cleared

**Comment by SimplyDanny** [comment]
In this context (adding a new password) you are right. Copied text is cleared when there is an interaction with the password field.

**Comment by jeyum2** [comment]
Then, is this interaction intended?
If it is intended, can we implement an option like "Don't clear when add new password"?

**Comment by SimplyDanny** [comment]
There are multiple situations where the content of the password field is automatically copied to the pasteboard during editing/adding a password:

* If the password field is entered/left.
* A new password is generated and entered into the field.
* On return from Safari ("Get a memorable one: xkpasswd") with something in the pasteboard after confirming to enter it into the password field.

I personally do not like all three of them since this behavior is not obvious to the user. Copying a password only on purpose should be sufficient and much safer. Besides that, any existing content in the pasteboard would not be cleared, as is what bothers you. 

@mssun, @yishilin14 what do you think?

**Comment by mssun** [comment]
Yes, I agree with "Copying a password only on purpose should be sufficient and much safer. "

I saw you have make a commit on fixing this. Please submit the PR, and I'll merge it ASAP. Thanks.
