### ISSUE TITLE
Problem cloning a repository without master branch

### ISSUE THREAD

**Issue by apfohl** [mssun/passforios#326]
I encountered a problem while cloning a repository that does not contain the branch `master`. If I try to clone, the application produces the following error. This also happens for a branch called `default`. Both are the only branches inside this repository while cloning it.

![IMG_7785](https://user-images.githubusercontent.com/480983/68413140-ec9dc300-018d-11ea-89e4-c3b2083fe173.PNG)

Can you point out, how a setup with multiple branches might look like? Or is this a bug?

Thanks in advance.

**Comment by SimplyDanny** [comment]
The problem is the missing `master` branch. The current implementation assumes that the checked out branch is called `master`. As a workaround you would need to add a `master` branch and check it out in your (remote) repository before you clone it from within the app. You can choose  a different branch name like `private`, `default`, etc. It will check out the specified branch in the process but needs the `master` to be present and checked out remotely. After the clone `master` can be safely deleted. It should work from thereon.

A PR to fix this issue is already in the works. 🙂
