### ISSUE TITLE
get pgp key to phone without webserver

### ISSUE THREAD

**Issue by Hans-Maulwurf** [mssun/passforios#50]
hey guys,
i try to test your app and stuck at the part of the pgp key. i dont have a webserver where i can upload my keys. so i wanted to use the ascii format. is there a way how i can get it from my linux system to the iphone? it's not jailbroken. but i dont want to send them by mail to my iphone. i tried to generate a qrcode, but the keys are too big for qrencode. do you have any hints?

**Comment by yishilin14** [comment]
Do you trust Dropbox or similar services? You may upload your keys (in the ASCII format) there, and copy them in your phone.

**Comment by Hans-Maulwurf** [comment]
Used two different services, thanks. Thought there would be another simple and secure way :D thanks

**Comment by mssun** [comment]
Hi, you can use iTunes to add keys. This method doesn't require a web service.

For the QR code, we have thought about it. The problem is that one picture may not cover all bytes of a key. It's possible to scan ~3 QR codes to input a key. We are still discussing whether to implement this. Anyways, uploading with iTunes is the safest method for now.

**Comment by Hans-Maulwurf** [comment]
btw: found this https://github.com/4bitfocus/asc-key-to-qr-code and it only needed 2 qrcodes for my public key.
