### ISSUE TITLE
App crashes when too much data is entered into Additions

### ISSUE THREAD

**Issue by nielsk** [mssun/passforios#57]
I added the following
User: username
TOTP-rescue-token 1
TOTP-rescue-token 2
…
TOTP-rescue-token 20

When I hit save, the app crashes. Without the 20 tokens it doesn't crash and everything works.

**Comment by mssun** [comment]
This is wired. Do you mean "TOTP-rescue-token: 1" but not "TOTP-rescue-token 1"? Cause the additional fields in "key: value" format are presented in a better UI style.

**Comment by nielsk** [comment]
I copied and pasted from another app on my iPhone, so it looked like this for the rescue tokens:

aaaa-aaaa
bbbb-bbbb
cccc-cccc
etc.

**Comment by yishilin14** [comment]
@nielsk I use [this site](http://www.unit-conversion.info/texttools/random-string-generator/) to generate several sets of 50 random strings. And the allowed characters are"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=~`". I failed to crash the app.

Do you have some texts that can repeatedly crash the app? Or, do you know which line of code that crashes the app? If you run iOS simulator using Xcode, when the app crashes, Xcode will bring you to that line of code. Those information would be really helpful.

My feeling is that the app may crash because of some other reasons. There seems to be some potential flaws in the app. Sometimes I crash the app accidentally when I am debugging some other features. We are working on improving the robustness of the app.

**Comment by nielsk** [comment]
*BSD- and Linux-user, so no XCode for me ;)

You copy the strings on iOS into the app? Or do you create the entry on your computer and sync over?

I just did the following:
create new entry
password: something
additions:
jaksdfök
jaksdfö
jkasdöfjö
jasdf
hsdfll
ajsdölkf
ajskdöf
ahdfjk
jsakdf
jaöskd
ajksödf

Save - Crash

ajskdöfj
ajdsköf

**Comment by nielsk** [comment]
I just tested more and the app crashed already when I entered anything into the additions, the app crashed for me oO

**Comment by yishilin14** [comment]
The weird thing is that I cannot crash the app in my iOS simulator. But I am able to crash the app in my iPhone...

More experiments
- iOS simulator: Add -> type a name -> paste the texts -> Save -> Everything looks find
- iOS simulator: Add ->paste the texts -> type a name -> Save -> Everything looks find
- iPhone: Add -> paste the texts ->  type a name -> Save -> Everything looks find
- iPhone: Add -> type a name -> paste the texts -> Save -> CRASH

Will look into this. Thank you for your magic texts!

**Comment by mssun** [comment]
Please try. Thanks.

**Comment by nielsk** [comment]
I will do so as soon as a new release is issued via TestFlight :)

**Comment by mssun** [comment]
Sure, thanks for your valuable report.

**Comment by nielsk** [comment]
It still crashes for me when I create a new entry and enter anything into the additions in 0.2.1

**Comment by nielsk** [comment]
Seems to be working now in 0.2.2 😺
