### ISSUE TITLE
Cannot change password length on Keychain style

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#84]
When trying to create a new password, and the Password Generator Flavor is "Apple", the slider for the password length is greyed out, and stuck at 15.

iOS 10.3.2
TestPilot version

**Comment by yishilin14** [comment]
We use [kishikawakatsumi/KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess) to generate passwords with the "Apple's Keychain Style". It generates random password that is in the same format used by [Safari AutoFill](https://support.apple.com/kb/PH21470?locale=zh_HK&viewlocale=en_US) (e.g., `xxx-xxx-xxx-xxx`). That's why the length is fixed. I am considering hiding the length setting button in this case, any suggestions?

**Comment by asymmetric** [comment]
Yes, it would be more intuitive as a user if the slider was hidden altogether.

**Comment by yishilin14** [comment]
Will fix this soon. Thanks. :-)

**Comment by yishilin14** [comment]
Fixed in the develop branch.
