### ISSUE TITLE
Increase max password length

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#86]
The current maximum is 24, which I find a bit too low, since I don't have to remember the password anyway.

As a reference, on 1Password for iOS it goes up to 64.

**Comment by yishilin14** [comment]
I did set max=64 in an earlier version (07782bd66283dd5542ede135ebe69acc51362c7f). However, setting max=64 makes the slider more difficult to use because there are too many values.

Personally, I don't need a password with length >=20.. I don't think increasing my password length to >=20 will provide much more security. Also, I don't use very long password in case I have to enter some of my passwords manually (say when I have to log into somewhere using a public computer/friends' computer). I will go crazy if I have to enter 64 random characters.

**Comment by yishilin14** [comment]
To be honest, I don't know what would be a proper maximum length.

**Comment by asymmetric** [comment]
The slider on 1Password on iOS works perfectly, that's why I mentioned it.

**Comment by yishilin14** [comment]
On LastPass for iOS it goes up to 64 too...

@mssun What about switching it back to 64? It is a "round number" in binary, and it just feels right.

**Comment by mssun** [comment]
Done. 70a41f64381a23f9bbeb1294f055a4c3edc7a011

Now, for random password, min = 4, max = 64.
