### ISSUE TITLE
Remove PGP key pair from iTunes Documents once imported

### ISSUE THREAD

**Issue by rnkn** [mssun/passforios#97]
If a user imports their PGP key pair via iTunes Documents, these remain accessible via any trusted computer (and can simply be dragged outside iTunes), which may provide an avenue for an attacker to export a user's private key, e.g.:

When an iPhone is plugged into a new computer via USB, the user is prompted with an option to trust the computer before the device can access the iPhone. As far as I can tell this preference is remembered for a long while. A user may unwittingly trust another person's computer/device, or a user may plug their iPhone into their own computer but leave the computer unattended. There are probably a bunch of reasons this could happen, and thus leave their key pair waiting for someone to find.

My proposed idea would be, once the app is launched and finds a PGP key pair, the key pair is imported into the app's private documents (replacing any existing PGP key pair) and removed from the iTunes Documents folder, thus no longer accessible via iTunes.

**Comment by yishilin14** [comment]
Hi, your suggestion sounds reasonable. Currently, ssh keys are also stored in the same "Documents" directory....

I am currently working on an "app extension" about iOS integration suggested in some other issues. Keys and the repository will be migrated to a "shared container" so that both the app and the app extension could access the data. The problem will be solved automatically when the extension is added to the app (may this week, or next week). I will pay attention to polish/test the "iTunes file sharing" related features.

**Comment by rnkn** [comment]
Excellent. Love your work 🔥

**Comment by rnkn** [comment]
Just tested this with current TestFlight version and it works. Thanks!
